### ISSUE TITLE
Error on Startup - failed to load

### ISSUE THREAD

**Issue by Fidulus** [ThinkingStudios/RyoamicLights#38]
**Describe the bug**
Screenshot

**Screenshots**
![image](https://github.com/user-attachments/assets/434cbb5c-e3d7-4d37-bfdf-b66e42c621a0)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft 21.0
 - Neoforge 21.0.114
 - lots of mods
 - Version 0.2.9 + mc1.2.1

- Crashlog: https://pastebin.com/T4w3mjQB

**Additional context**
I am very sorry if this error is related to another mod. I would be very happy to provide any more info if necessary. I am not very good at reading the error logs, but i hope you have the patience and dedication to help me out anyway. Thank you very much.
I love the mod, because as of now it is the ONLY way to get dynamic lights in neoforge 21.0.x

**Comment by 3gf8jv4dv** [comment]
For some reason, `ryoamiclights.toml` is written with the same paragraph twice. This caused some kind of problem reading the config file.

Reproducible in NeoForge 21.0.114-beta using only RyoamicLights and ObsidianUI. The paragraph only appears once when entering the game, and a second one will appear after entering a world. So if using the latest version of NeoForge and mods, the first time you enter a world it will not crash, but the second time you launch the game it will crash.

Maybe it is because of some breaking changes in NeoForge? I thought I would test it out.

```
[light_sources]
	water_sensitive_check = true
	self = true
	block_entities = true
	entities = true
[light_sources]
	water_sensitive_check = true
	self = true
	block_entities = true
	entities = true
```

**Comment by 3gf8jv4dv** [comment]
It can be confirmed that this is caused by a breaking change in NeoForge. The problem started to occur starting with NeoForge 21.0.82-beta.

**RELATED:**
- https://github.com/neoforged/NeoForge/pull/1239
- https://github.com/neoforged/FancyModLoader/pull/172

**Comment by NovaViper** [comment]
It's still broken even after update v0.2.10, the buggy config that @3gf8jv4dv mention is still being created even on NeoForge v21.0.167, which results in the game crashing after you relaunch it.
